name: music_instruments
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+4
  firebase_storage: ^11.1.1
  cloud_firestore: ^4.5.3
  firebase_core: ^2.10.0
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.3
  shared_preferences: ^2.1.0
  connectivity_plus: ^3.0.4
  http: ^0.13.5
  flutter_svg: ^2.0.5
  audioplayers: ^4.0.1
  file_picker: ^5.2.11
  fluttertoast: ^8.2.1
  just_audio: ^0.9.32
  audio_video_progress_bar: ^1.0.1
  flutter_staggered_animations: ^1.1.1
  screensize_utils:
    git:
      url: https://github.com/Ipilot7/ScreenSizeUtil.git
      ref: main # branch name



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/


  fonts:
    - family: Bangers
      fonts:
        - asset: assets/fonts/Bangers-Regular.ttf

    - family: GreatVibes
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.ttf    
        - asset: assets/fonts/inter/Inter-Bold.ttf    
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf    
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf    
        - asset: assets/fonts/inter/Inter-Light.ttf    
        - asset: assets/fonts/inter/Inter-Medium.ttf    
        - asset: assets/fonts/inter/Inter-Regular.ttf    
        - asset: assets/fonts/inter/Inter-SemiBold.ttf    
        - asset: assets/fonts/inter/Inter-Thin.ttf    
  